version: '2'
services:
  mongodb:
    hostname: mongodb
    domainname: elk-local
    image: mongo
    ports:
      - 27017:27017
    network_mode: "host"
    volumes:
      - /data:/data
  elasticsearch:
    hostname: elasticsearch
    domainname: elk-local
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - 9200:9200
    network_mode: "host"
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
  kibana:
    hostname: kibana
    domainname: elk-local
    image: docker.elastic.co/kibana/kibana:5.5.1
    ports:
      - "8080:5601"
    network_mode: "host"
    environment:
      - ELASTICSEARCH_URL="http://localhost:9200"
  indexer:
    hostname: indexer
    domainname: elk-local
    image: julianogalgaro/indexer:latest
    network_mode: "host"
  classificator:
    hostname: classificator
    domainname: elk-local
    image: julianogalgaro/classificator:latest
    network_mode: "host"
  tweet:
    hostname: tweet
    domainname: elk-local
    image: julianogalgaro/tweet:latest
    network_mode: "host"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    environment:
      - "TWITTER_CONSUMER_API_KEY="
      - "TWITTER_CONSUMER_API_SECRET="
      - "TWITTER_ACCESS_TOKEN="
      - "TWITTER_ACCESS_TOKEN_SECRET="
volumes:
  data:
    driver: local
  esdata:
    driver: local

